export const countryList =
	[
		"French Polynesia",
		"Algeria",
		"Denmark",
		"South Africa",
		"United Arab Emirates",
		"Russia",
		"China",
		"Brazil",
		"Yemen",
		"Russian Federation",
		"Spain",
		"Iran",
		"United States",
		"Ivory Coast",
		"Ethiopia",
		"Australia",
		"Egypt",
		"Saudi Arabia",
		"Nigeria",
		"United Kingdom",
		"Mexico",
		"Ghana",
		"Switzerland",
		"Turkey",
		"Jordan",
		"Colombia",
		"Chad",
		"Argentina",
		"Norway",
		"Iceland",
		"Uzbekistan",
		"Solomon Islands",
		"Morocco",
		"France",
		"Sweden",
		"Papua New Guinea",
		"Greenland",
		"India",
		"Paraguay",
		"Venezuela",
		"Italy",
		"Honduras",
		"Cook Islands",
		"Comoros",
		"Libya",
		"Japan",
		"New Zealand",
		"Canada",
		"Kazakhstan",
		"Myanmar",
		"Syria",
		"Indonesia",
		"Netherlands",
		"Madagascar",
		"Chile",
		"Belgium",
		"Antigua and Barbuda",
		"Germany",
		"Greece",
		"Malaysia",
		"Mozambique",
		"Samoa",
		"Peru",
		"Tanzania",
		"Romania",
		"Turkmenistan",
		"Bahamas",
		"St. Helena",
		"Eritrea",
		"Kenya",
		"Sudan",
		"Mauritania",
		"Aruba",
		"Vanuatu",
		"Anguilla",
		"Dominican Republic",
		"Philippines",
		"Bahrain",
		"Botswana",
		"Somalia",
		"Cuba",
		"Costa Rica",
		"Bermuda",
		"Nepal",
		"Serbia",
		"Lebanon",
		"Thailand",
		"Central African Republic",
		"Barbados",
		"Iraq",
		"Pakistan",
		"Marshall Islands",
		"Gambia",
		"Burundi",
		"Mali",
		"Congo",
		"Malawi",
		"Vietnam",
		"New Caledonia",
		"Bosnia and Herzegovina",
		"Panama",
		"Bulgaria",
		"Netherlands Antilles",
		"Burkina Faso",
		"Czech Republic",
		"Equatorial Guinea",
		"Slovakia",
		"Hungary",
		"Zimbabwe",
		"Georgia",
		"Cape Verde",
		"Croatia",
		"Brunei",
		"Mongolia",
		"Belize",
		"Poland",
		"Bangladesh",
		"Angola",
		"Haiti",
		"French Guiana",
		"Bolivia",
		"Cocos (Keeling) Islands",
		"Ireland",
		"Zambia",
		"Saint Vincent and the Grenadines",
		"South Korea",
		"Guinea",
		"Sri Lanka",
		"Benin",
		"Senegal",
		"Ecuador",
		"Portugal",
		"Ukraine",
		"Kiribati",
		"Cayman Islands",
		"Taiwan",
		"Dominica",
		"Tunisia",
		"Cameroon",
		"Qatar",
		"Tajikistan",
		"Mayotte",
		"Uganda",
		"Cyprus",
		"British Virgin Islands",
		"Finland",
		"Namibia",
		"Israel",
		"Tonga",
		"Armenia",
		"Faroe Islands",
		"Martinique",
		"Democratic Republic of Congo",
		"Sierra Leone",
		"North Korea",
		"Guatemala",
		"Kyrgyzstan",
		"Saint Pierre and Miquelon",
		"Tuvalu",
		"Wallis and Futuna Islands",
		"Maldives",
		"Gabon",
		"Guadeloupe",
		"Turks And Caicos Islands",
		"Guyana",
		"Gibraltar",
		"Grenada",
		"Austria",
		"Azerbaijan",
		"Afghanistan",
		"Hong Kong",
		"Lao People's Democratic Republic",
		"Fiji",
		"Nauru",
		"Niue",
		"Djibouti",
		"Estonia",
		"Rwanda",
		"Oman",
		"Jamaica",
		"Moldova",
		"Federated States of Micronesia",
		"Lithuania",
		"Kuwait",
		"Togo",
		"Slovenia",
		"Laos",
		"Latvia",
		"Luxembourg",
		"Monaco",
		"Macau",
		"Nicaragua",
		"Belarus",
		"Malta",
		"Liberia",
		"Falkland Islands",
		"Mauritius",
		"Lesotho",
		"Swaziland",
		"Uruguay",
		"Saint Kitts and Nevis",
		"Niger",
		"Norfolk Island",
		"Cote D'Ivoire",
		"Macedonia",
		"Guinea-Bissau",
		"Cambodia",
		"Bhutan",
		"Suriname",
		"Trinidad and Tobago",
		"Seychelles",
		"Palau",
		"Reunion",
		"El Salvador",
		"Singapore",
		"St. Lucia",
		"Montenegro",
		"Albania",
		"Libyan Arab Jamahiriya",
		"Northern Mariana Islands",
		"Sao Tome and Principe",
		"Western Sahara",
		"Christmas Island",
		"Macao",
		"Antarctica",
	];	